/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package logi;


import Conexion.Metodos_sql;
import Metodos.TextPrompt;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Jorge
 */
public class CrearCuenta extends javax.swing.JFrame {

    Metodos_sql metodosSql = new Metodos_sql();
    Login log = new Login();
    Color rojoo = new Color(255,142,142);
    Color rojis = new Color(248,66,85);
    Color blancoo = new Color(255,255,255);
    Color verdesito = new Color(84,180,106);
    private boolean aceptar;
    /**
     * Creates new form CrearCuenta
     */
    public CrearCuenta() {
        initComponents();
        TextPrompt txt = new TextPrompt("Campo obligatorio",jTextNombre);
        TextPrompt txt1 = new TextPrompt("Campo obligatorio",jTextApellido);
        TextPrompt txt2 = new TextPrompt("Campo obligatorio",jTextContraseña);
        TextPrompt txt3 = new TextPrompt("Campo obligatorio",jTextConfirmarContraseña);
        TextPrompt txt4 = new TextPrompt("Campo obligatorio",jTextCorreo);
        TextPrompt txt5 = new TextPrompt("Campo obligatorio",jTextUsuario);
        log.iconImagen();
    }

    public void validar(){
        if(jTextNombre.getText().isEmpty()){
            jTextNombre.setBackground(rojoo);
        }
        if(jTextApellido.getText().isEmpty()){
            jTextApellido.setBackground(rojoo);
        }
        if(jTextUsuario.getText().isEmpty()){
            jTextUsuario.setBackground(rojoo);
        }
        if(jTextContraseña.getText().isEmpty()){
            jTextContraseña.setBackground(rojoo);
        }
        if(jTextConfirmarContraseña.getText().isEmpty()){
            jTextConfirmarContraseña.setBackground(rojoo);
        }
        
        if(jTextCorreo.getText().isEmpty()){
            jTextCorreo.setBackground(rojoo);
            aceptar = true;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelNom = new javax.swing.JLabel();
        jLabelCon = new javax.swing.JLabel();
        jLabelCof = new javax.swing.JLabel();
        jLabelCor = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButtonLogin = new javax.swing.JButton();
        jTextNombre = new javax.swing.JTextField();
        jTextContraseña = new javax.swing.JPasswordField();
        jTextConfirmarContraseña = new javax.swing.JPasswordField();
        jTextCorreo = new javax.swing.JTextField();
        jLabelApe = new javax.swing.JLabel();
        jTextApellido = new javax.swing.JTextField();
        jLabelUsu = new javax.swing.JLabel();
        jTextUsuario = new javax.swing.JTextField();
        jLabelNombre = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelContraseña = new javax.swing.JLabel();
        jLabelConfContraseña = new javax.swing.JLabel();
        jLabelCorreo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(670, 458));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Crear cuenta");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 125, -1));

        jLabelNom.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabelNom.setText("Nombre");
        jPanel1.add(jLabelNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, 26));

        jLabelCon.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabelCon.setText("Contraseña");
        jPanel1.add(jLabelCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabelCof.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabelCof.setText("Confirmar contraseña");
        jPanel1.add(jLabelCof, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, -1, -1));

        jLabelCor.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabelCor.setText("Correo electronico");
        jPanel1.add(jLabelCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jButton1.setBackground(new java.awt.Color(249, 24, 83));
        jButton1.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Crear");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, 120, 30));

        jButtonLogin.setBackground(new java.awt.Color(242, 242, 242));
        jButtonLogin.setForeground(new java.awt.Color(102, 102, 102));
        jButtonLogin.setText("Tienes cuenta? Inicia Sesion");
        jButtonLogin.setBorder(null);
        jButtonLogin.setBorderPainted(false);
        jButtonLogin.setContentAreaFilled(false);
        jButtonLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonLoginMouseExited(evt);
            }
        });
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, -1, -1));

        jTextNombre.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextNombre.setBorder(null);
        jTextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreActionPerformed(evt);
            }
        });
        jTextNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextNombreKeyReleased(evt);
            }
        });
        jPanel1.add(jTextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 233, 29));

        jTextContraseña.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextContraseña.setBorder(null);
        jTextContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextContraseñaActionPerformed(evt);
            }
        });
        jTextContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextContraseñaKeyReleased(evt);
            }
        });
        jPanel1.add(jTextContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 233, 29));

        jTextConfirmarContraseña.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextConfirmarContraseña.setBorder(null);
        jTextConfirmarContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextConfirmarContraseñaKeyReleased(evt);
            }
        });
        jPanel1.add(jTextConfirmarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, 259, 29));

        jTextCorreo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextCorreo.setBorder(null);
        jTextCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextCorreoKeyReleased(evt);
            }
        });
        jPanel1.add(jTextCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 316, 29));

        jLabelApe.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabelApe.setText("Apellido");
        jPanel1.add(jLabelApe, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, -1, -1));

        jTextApellido.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextApellido.setBorder(null);
        jTextApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextApellidoKeyReleased(evt);
            }
        });
        jPanel1.add(jTextApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 256, 29));

        jLabelUsu.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabelUsu.setText("Usuario");
        jPanel1.add(jLabelUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jTextUsuario.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextUsuario.setBorder(null);
        jTextUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextUsuarioKeyReleased(evt);
            }
        });
        jPanel1.add(jTextUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 233, 28));

        jLabelNombre.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(681, 51, 61, -1));

        jLabelApellido.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(jLabelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(681, 165, -1, -1));

        jLabelUsuario.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(jLabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(681, 206, -1, -1));

        jLabelContraseña.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(jLabelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(681, 240, -1, -1));

        jLabelConfContraseña.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(jLabelConfContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(681, 268, -1, -1));

        jLabelCorreo.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(jLabelCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 301, 53, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 230, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 230, 10));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 230, 10));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 250, 10));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 260, -1));

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 320, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 62, 750, 398));

        jPanel2.setBackground(new java.awt.Color(23, 35, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 146, 460));

        jPanel3.setBackground(new java.awt.Color(71, 120, 197));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 0, 750, 60));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextUsuarioKeyReleased
        if(jTextUsuario.getText().isEmpty()){
            jTextUsuario.setBackground(rojoo);
        }else{
            int result = metodosSql.compararUsuario(jTextUsuario.getText());
            if(result==1){
                jTextUsuario.setBackground(rojis);
            }else{
                jTextUsuario.setBackground(verdesito);
            }
        }  
    }//GEN-LAST:event_jTextUsuarioKeyReleased

    private void jTextApellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextApellidoKeyReleased
        if(jTextApellido.getText().isEmpty()){
            jTextApellido.setBackground(rojoo);
        }else{
            jTextApellido.setBackground(blancoo);
        }
    }//GEN-LAST:event_jTextApellidoKeyReleased

    private void jTextCorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCorreoKeyReleased
        if(jTextCorreo.getText().isEmpty()){
            jTextCorreo.setBackground(blancoo);
        }else{
            if(!jTextCorreo.getText().contains("@") || !jTextCorreo.getText().contains(".")){
                jTextCorreo.setBackground(rojis);
            }else{
                jTextCorreo.setBackground(blancoo);
            }
        }
    }//GEN-LAST:event_jTextCorreoKeyReleased

    private void jTextConfirmarContraseñaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextConfirmarContraseñaKeyReleased
        if(jTextConfirmarContraseña.getText().isEmpty()){
            jTextConfirmarContraseña.setBackground(blancoo);
        }else{
            if(!jTextContraseña.getText().equals(jTextConfirmarContraseña.getText())){
                jTextConfirmarContraseña.setBackground(rojis);
            }else{
                jTextConfirmarContraseña.setBackground(verdesito);
            }
        }
    }//GEN-LAST:event_jTextConfirmarContraseñaKeyReleased

    private void jTextContraseñaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextContraseñaKeyReleased
        if(jTextContraseña.getText().isEmpty()){
            jTextContraseña.setBackground(rojoo);
        }else{
            jTextContraseña.setBackground(blancoo);
        }
    }//GEN-LAST:event_jTextContraseñaKeyReleased

    private void jTextContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextContraseñaActionPerformed

    private void jTextNombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNombreKeyReleased
        if(jTextNombre.getText().isEmpty()){
            jTextNombre.setBackground(rojoo);
        }else{
            jTextNombre.setBackground(blancoo);
        } 
    }//GEN-LAST:event_jTextNombreKeyReleased

    private void jTextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        String contraseña = jTextContraseña.getText();
        String confContraseña = jTextConfirmarContraseña.getText();
        String nombre = jTextNombre.getText();
        String apellido = jTextApellido.getText();
        String email = jTextCorreo.getText();
        String usuario = jTextUsuario.getText();
        if(nombre.isEmpty() && contraseña.isEmpty() && confContraseña.isEmpty() && apellido.isEmpty() && email.isEmpty() && usuario.isEmpty()){
            this.dispose();
            log.setVisible(true);
        }else{
            int dialog = JOptionPane.YES_NO_OPTION;
            int result = JOptionPane.showConfirmDialog(null, "Hay campos llenados Seguro que quieres salir?", "EXIT", dialog);
            if(result == 0){
                this.dispose();
                log.setVisible(true);
            }
        }
        
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jButtonLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginMouseExited
        Color griss = new Color(102,102,102);
        jButtonLogin.setForeground(griss);
    }//GEN-LAST:event_jButtonLoginMouseExited

    private void jButtonLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLoginMouseEntered
        Color blackk = new Color(0,0,0);
        jButtonLogin.setForeground(blackk);
    }//GEN-LAST:event_jButtonLoginMouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String contraseña = jTextContraseña.getText();
        String confContraseña = jTextConfirmarContraseña.getText();
        String nombre = jTextNombre.getText();
        String apellido = jTextApellido.getText();
        String email = jTextCorreo.getText();
        String usuario = jTextUsuario.getText();
        validar();
        if(contraseña.equals("") || confContraseña.equals("") || nombre.equals("") || apellido.equals("") || email.equals("") || usuario.equals("")){
            JOptionPane.showMessageDialog(null,"Los campos resaltados son obligatorios");
        }else{
            if(aceptar){
                JOptionPane.showMessageDialog(null,"Correo no valido");
            }else{
                if(contraseña.equals(confContraseña)){
                    int result = metodosSql.compararUsuario(usuario);
                    if(result==0){
                        int i = metodosSql.guardar(nombre, apellido, email, contraseña, usuario);
                        if(i>0){
                            JOptionPane.showMessageDialog(this,"¡Cuenta creada exitosamente!");
                            jTextContraseña.setText("");
                            jTextConfirmarContraseña.setText("");
                            jTextNombre.setText("");
                            jTextApellido.setText("");
                            jTextCorreo.setText("");
                            jTextUsuario.setText("");
                        }else{
                            JOptionPane.showMessageDialog(this,"¡Error en la creacion de cuenta!");
                        }
                    }else{
                        JOptionPane.showMessageDialog(null, "Ese usuario ya existe. Ingrese otro");
                    }
                }else{
                    JOptionPane.showMessageDialog(null,"Las contraseñas no coinciden");
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelApe;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelCof;
    private javax.swing.JLabel jLabelCon;
    private javax.swing.JLabel jLabelConfContraseña;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelCor;
    private javax.swing.JLabel jLabelCorreo;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelUsu;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTextApellido;
    private javax.swing.JPasswordField jTextConfirmarContraseña;
    private javax.swing.JPasswordField jTextContraseña;
    private javax.swing.JTextField jTextCorreo;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextUsuario;
    // End of variables declaration//GEN-END:variables
}
