/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package logi;

import Conexion.Metodos_sql;
import Metodos.TextPrompt;
import java.awt.Color;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import AppPackage.AnimationClass;
import Metodos.JAnimation;
import Ventanas.Form_principal;
import java.awt.event.ActionEvent;
import javax.swing.Timer;
/**
 *
 * @author Jorge
 */
public final class Login extends javax.swing.JFrame {

    Metodos_sql metodoSql = new Metodos_sql();
    Color rojoo = new Color(255,142,142);
    Color rojis = new Color(248,66,85);
    Color blancoo = new Color(255,255,255);
    Color verdesito = new Color(84,180,106);
    private boolean aceptar;
    JAnimation animacion = new JAnimation();
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        TextPrompt text = new TextPrompt("Usuario",jTextNombre);
        TextPrompt text1 = new TextPrompt("Password",jTextContraseña);
        TextPrompt txt = new TextPrompt("Campo obligatorio",jTextNombre1);
        TextPrompt txt1 = new TextPrompt("Campo obligatorio",jTextApellido);
        TextPrompt txt2 = new TextPrompt("Campo obligatorio",jTextContraseña1);
        TextPrompt txt3 = new TextPrompt("Campo obligatorio",jTextConfirmarContraseña);
        TextPrompt txt4 = new TextPrompt("Campo obligatorio",jTextCorreo);
        TextPrompt txt5 = new TextPrompt("Campo obligatorio",jTextUsuario);
        iconImagen();
        animacionInicial().start();
    }
    
    public Timer animacionInicial(){
        Timer time = new Timer(8000, (ActionEvent e) -> {
            AnimationClass animat = new AnimationClass();    
            if(jLabelImagen.getX() == 100){
                //primero
                jLabelImagen.setLocation(-400, 0);
                animat.jLabelXRight(-400, 100, 10, 10, jLabelImagen1);
            }
            if(jLabelImagen1.getX() == 100){
                //segundo
                jLabelImagen1.setLocation(-400, 0);
                animat.jLabelXRight(-400, 100, 10, 10, jLabelImagen2);
            }
            if(jLabelImagen2.getX() == 100){
                //tercero
                jLabelImagen2.setLocation(-400, 10);
                animat.jLabelXRight(-400, 100, 10, 10, jLabelImagen3);
            }
            if(jLabelImagen3.getX() == 100){
                //cuarto
                jLabelImagen3.setLocation(-400, -90);
                animat.jLabelXRight(-400, 100, 10, 10, jLabelImagen);
            }
        });
        return time;
    }
    
    public void limpiar(){
        jTextNombre1.setBackground(Color.white);
        jTextUsuario.setBackground(Color.white);
        jTextContraseña1.setBackground(Color.white);
        jTextConfirmarContraseña.setBackground(Color.white);
        jTextApellido.setBackground(Color.white);
        jTextCorreo.setBackground(Color.white);
        
        jTextContraseña1.setText("");
        jTextConfirmarContraseña.setText("");
        jTextNombre1.setText("");
        jTextApellido.setText("");
        jTextCorreo.setText("");
        jTextUsuario.setText("");
    }
    
    Color rojoos = new Color(249,24,83);
    
    int contador=0;
    
    public void validar(){
        if(jTextNombre1.getText().isEmpty()){
            jTextNombre1.setBackground(rojoo);
        }
        if(jTextApellido.getText().isEmpty()){
            jTextApellido.setBackground(rojoo);
        }
        if(jTextUsuario.getText().isEmpty()){
            jTextUsuario.setBackground(rojoo);
        }
        if(jTextContraseña1.getText().isEmpty()){
            jTextContraseña1.setBackground(rojoo);
        }
        if(jTextConfirmarContraseña.getText().isEmpty()){
            jTextConfirmarContraseña.setBackground(rojoo);
        }
        
        if(jTextCorreo.getText().isEmpty()){
            jTextCorreo.setBackground(rojoo);
            aceptar = true;
        }
    }

    public void iconImagen(){
        URL url = getClass().getResource("/Img/icon_sistema.png");
        ImageIcon iconoImagen = new ImageIcon(url);
        this.setIconImage(iconoImagen.getImage());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanelBarra = new javax.swing.JPanel();
        jButtonCerrar = new javax.swing.JButton();
        jButtonMinimizar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanelPrincipal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jButtonIngresar = new javax.swing.JButton();
        jTextContraseña = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jPanelInterface = new javax.swing.JPanel();
        jLabelImagen = new javax.swing.JLabel();
        jLabelImagen1 = new javax.swing.JLabel();
        jLabelImagen2 = new javax.swing.JLabel();
        jLabelImagen3 = new javax.swing.JLabel();
        jButtonCrearCuenta = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanelCrear = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabelNom = new javax.swing.JLabel();
        jTextNombre1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelUsu = new javax.swing.JLabel();
        jTextUsuario = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabelApe = new javax.swing.JLabel();
        jTextApellido = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabelCon = new javax.swing.JLabel();
        jTextContraseña1 = new javax.swing.JPasswordField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabelCor = new javax.swing.JLabel();
        jTextCorreo = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jButtonCancelar = new javax.swing.JButton();
        jTextConfirmarContraseña = new javax.swing.JPasswordField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabelCof = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButtonCrear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelBarra.setBackground(new java.awt.Color(253, 253, 253));

        jButtonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icon_close.png"))); // NOI18N
        jButtonCerrar.setBorder(null);
        jButtonCerrar.setBorderPainted(false);
        jButtonCerrar.setContentAreaFilled(false);
        jButtonCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCerrar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icon_select_close.png"))); // NOI18N
        jButtonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCerrarMouseClicked(evt);
            }
        });
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });

        jButtonMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icon_minim.png"))); // NOI18N
        jButtonMinimizar.setBorder(null);
        jButtonMinimizar.setBorderPainted(false);
        jButtonMinimizar.setContentAreaFilled(false);
        jButtonMinimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMinimizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icon_select_minim.png"))); // NOI18N
        jButtonMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonMinimizarMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel4.setText("Log In");

        javax.swing.GroupLayout jPanelBarraLayout = new javax.swing.GroupLayout(jPanelBarra);
        jPanelBarra.setLayout(jPanelBarraLayout);
        jPanelBarraLayout.setHorizontalGroup(
            jPanelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBarraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 945, Short.MAX_VALUE)
                .addComponent(jButtonMinimizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelBarraLayout.setVerticalGroup(
            jPanelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBarraLayout.createSequentialGroup()
                .addGroup(jPanelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonCerrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMinimizar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel3.add(jPanelBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 28));

        jPanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        jPanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/iconUsuario.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setPreferredSize(new java.awt.Dimension(512, 512));
        jPanelPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 32, 32));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/iconPassword.png"))); // NOI18N
        jLabel2.setToolTipText("");
        jPanelPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        jTextNombre.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextNombre.setBorder(null);
        jTextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreActionPerformed(evt);
            }
        });
        jPanelPrincipal.add(jTextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 248, 32));

        jButtonIngresar.setBackground(new java.awt.Color(249, 24, 83));
        jButtonIngresar.setFont(new java.awt.Font("Roboto Medium", 1, 16)); // NOI18N
        jButtonIngresar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIngresar.setText("Iniciar Sesión");
        jButtonIngresar.setBorder(null);
        jButtonIngresar.setBorderPainted(false);
        jButtonIngresar.setMargin(new java.awt.Insets(3, 14, 3, 14));
        jButtonIngresar.setName(""); // NOI18N
        jButtonIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonIngresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonIngresarMouseExited(evt);
            }
        });
        jButtonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngresarActionPerformed(evt);
            }
        });
        jPanelPrincipal.add(jButtonIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 169, 28));

        jTextContraseña.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextContraseña.setBorder(null);
        jPanelPrincipal.add(jTextContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 248, 32));

        jLabel3.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/iconAccount.png"))); // NOI18N
        jPanelPrincipal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jTextField1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jTextField1.setText("Inicio de Sesion");
        jTextField1.setBorder(null);
        jPanelPrincipal.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setPreferredSize(new java.awt.Dimension(50, 20));
        jPanelPrincipal.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 212, 250, 10));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanelPrincipal.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 282, 250, 10));

        jPanel3.add(jPanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, 310, 470));

        jPanelInterface.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/img_fondo4.png"))); // NOI18N
        jPanelInterface.add(jLabelImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(-400, 0, 400, 440));

        jLabelImagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/img_fondo1.png"))); // NOI18N
        jPanelInterface.add(jLabelImagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-400, 20, 400, 350));

        jLabelImagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/img_fondo2.png"))); // NOI18N
        jPanelInterface.add(jLabelImagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-400, 10, 400, 370));

        jLabelImagen3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/img_fondo3.png"))); // NOI18N
        jPanelInterface.add(jLabelImagen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-400, -90, 400, 460));

        jButtonCrearCuenta.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButtonCrearCuenta.setForeground(new java.awt.Color(102, 102, 102));
        jButtonCrearCuenta.setText("No tienes cuenta? Create una");
        jButtonCrearCuenta.setBorder(null);
        jButtonCrearCuenta.setBorderPainted(false);
        jButtonCrearCuenta.setContentAreaFilled(false);
        jButtonCrearCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCrearCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonCrearCuentaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonCrearCuentaMouseExited(evt);
            }
        });
        jButtonCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearCuentaActionPerformed(evt);
            }
        });
        jPanelInterface.add(jButtonCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/fondo_login.png"))); // NOI18N
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelInterface.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-160, 0, 930, 470));

        jPanel3.add(jPanelInterface, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 770, 470));

        jPanelCrear.setBackground(new java.awt.Color(255, 255, 255));
        jPanelCrear.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Crear cuenta");
        jPanelCrear.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 160, -1));

        jLabelNom.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabelNom.setForeground(new java.awt.Color(71, 120, 197));
        jLabelNom.setText("Nombre");
        jPanelCrear.add(jLabelNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, 26));

        jTextNombre1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextNombre1.setBorder(null);
        jTextNombre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombre1ActionPerformed(evt);
            }
        });
        jTextNombre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextNombre1KeyReleased(evt);
            }
        });
        jPanelCrear.add(jTextNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 233, 29));

        jSeparator1.setForeground(new java.awt.Color(71, 120, 197));
        jPanelCrear.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 230, 3));

        jLabelUsu.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabelUsu.setForeground(new java.awt.Color(71, 120, 197));
        jLabelUsu.setText("Usuario");
        jPanelCrear.add(jLabelUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        jTextUsuario.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextUsuario.setBorder(null);
        jTextUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextUsuarioKeyReleased(evt);
            }
        });
        jPanelCrear.add(jTextUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 233, 28));

        jSeparator4.setForeground(new java.awt.Color(71, 120, 197));
        jPanelCrear.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 230, 10));

        jLabelApe.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabelApe.setForeground(new java.awt.Color(71, 120, 197));
        jLabelApe.setText("Apellido");
        jPanelCrear.add(jLabelApe, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, -1));

        jTextApellido.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextApellido.setBorder(null);
        jTextApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextApellidoKeyReleased(evt);
            }
        });
        jPanelCrear.add(jTextApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 256, 29));

        jSeparator5.setForeground(new java.awt.Color(71, 120, 197));
        jPanelCrear.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 250, 10));

        jLabelCon.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabelCon.setForeground(new java.awt.Color(71, 120, 197));
        jLabelCon.setText("Contraseña");
        jPanelCrear.add(jLabelCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jTextContraseña1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextContraseña1.setBorder(null);
        jTextContraseña1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextContraseña1ActionPerformed(evt);
            }
        });
        jTextContraseña1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextContraseña1KeyReleased(evt);
            }
        });
        jPanelCrear.add(jTextContraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 233, 29));

        jSeparator6.setForeground(new java.awt.Color(71, 120, 197));
        jPanelCrear.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 230, 10));

        jLabelCor.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabelCor.setForeground(new java.awt.Color(71, 120, 197));
        jLabelCor.setText("Correo electronico");
        jPanelCrear.add(jLabelCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jTextCorreo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextCorreo.setBorder(null);
        jTextCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextCorreoKeyReleased(evt);
            }
        });
        jPanelCrear.add(jTextCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 316, 29));

        jSeparator7.setForeground(new java.awt.Color(71, 120, 197));
        jPanelCrear.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 320, 10));

        jButtonCancelar.setBackground(new java.awt.Color(249, 24, 83));
        jButtonCancelar.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setBorder(null);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanelCrear.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 420, 120, 30));

        jTextConfirmarContraseña.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jTextConfirmarContraseña.setBorder(null);
        jTextConfirmarContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextConfirmarContraseñaKeyReleased(evt);
            }
        });
        jPanelCrear.add(jTextConfirmarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 259, 29));

        jSeparator8.setForeground(new java.awt.Color(71, 120, 197));
        jPanelCrear.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 330, 260, -1));

        jLabelCof.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jLabelCof.setForeground(new java.awt.Color(71, 120, 197));
        jLabelCof.setText("Confirmar contraseña");
        jPanelCrear.add(jLabelCof, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, -1, -1));

        jLabel7.setBackground(new java.awt.Color(71, 120, 197));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/wallpaper_img.jpg"))); // NOI18N
        jPanelCrear.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 100));

        jButtonCrear.setBackground(new java.awt.Color(249, 24, 83));
        jButtonCrear.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jButtonCrear.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCrear.setText("Crear");
        jButtonCrear.setBorder(null);
        jButtonCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonCrearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonCrearMouseExited(evt);
            }
        });
        jButtonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCrearActionPerformed(evt);
            }
        });
        jPanelCrear.add(jButtonCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 120, 30));

        jPanel3.add(jPanelCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -470, 770, 470));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngresarActionPerformed
        animacionInicial().stop();
        String nombre = jTextNombre.getText();
        String contraseña = jTextContraseña.getText();
        if(nombre.equals("") || contraseña.equals("")){
            JOptionPane.showMessageDialog(null,"¡Debe llenar las dos casillas!");
        }else{
            if(contador<3){
                if(nombre.equals("Administrador") && contraseña.equals("root")){
                    Form_principal ventana = new Form_principal();
                    this.dispose();
                    ventana.setVisible(true);
                }else{
                    String busca = Metodos_sql.buscarUsuario(nombre, contraseña);
                    if(busca.equals("Bienvenido")){
                        String nom = Metodos_sql.buscarNombre(nombre);
                        JOptionPane.showMessageDialog(null,"Bienvenido "+nom);
                        Cuenta cuentapanel = new Cuenta();
                        cuentapanel.jMenuUsuario.setText("Usuario: "+nom);
                        this.dispose();
                        cuentapanel.setVisible(true);
                        cuentapanel.setjLabelBienvenida(nom);
                        cuentapanel.setExtendedState(cuentapanel.MAXIMIZED_BOTH);
                    }else{
                        contador++;
                        JOptionPane.showMessageDialog(null,"Datos Invalidos intento "+contador);
                    }
                }
            }else{
                JOptionPane.showMessageDialog(null,"Numero de intentos exedidos");
                this.dispose();
            }
        }  
        
    }//GEN-LAST:event_jButtonIngresarActionPerformed

    private void jTextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreActionPerformed

    private void jButtonCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearCuentaActionPerformed
        animacionInicial().stop();
        animacion.jPanelXIzquierda(0, -770, 10, 5, jPanelInterface);
        animacion.jPanelYAbajo(-470, 30, 10, 5, jPanelCrear);
        /*animacionInicial().stop();
        CrearCuenta crear = new CrearCuenta();
        this.dispose();
        crear.setVisible(true);
        crear.setTitle("Crear cuenta");*/
    }//GEN-LAST:event_jButtonCrearCuentaActionPerformed

    private void jButtonIngresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIngresarMouseEntered
        jButtonIngresar.setBackground(Color.white);
        jButtonIngresar.setForeground(rojoos);
    }//GEN-LAST:event_jButtonIngresarMouseEntered

    private void jButtonIngresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonIngresarMouseExited
        jButtonIngresar.setBackground(rojoos);
        jButtonIngresar.setForeground(Color.white);
    }//GEN-LAST:event_jButtonIngresarMouseExited

    private void jButtonCrearCuentaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCrearCuentaMouseEntered
        Color whitess = new Color(154,154,154);
        jButtonCrearCuenta.setForeground(whitess);
    }//GEN-LAST:event_jButtonCrearCuentaMouseEntered

    private void jButtonCrearCuentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCrearCuentaMouseExited
        Color griss = new Color(102,102,102);
        jButtonCrearCuenta.setForeground(griss);
    }//GEN-LAST:event_jButtonCrearCuentaMouseExited

    private void jButtonCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCerrarMouseClicked
        int dialog = JOptionPane.YES_NO_OPTION;
        int result = JOptionPane.showConfirmDialog(null, "Seguro que quiere Salir", "EXIT", dialog);
        if(result == 0)
            System.exit(0);
    }//GEN-LAST:event_jButtonCerrarMouseClicked

    private void jButtonMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMinimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_jButtonMinimizarMouseClicked

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        for (double i = 0.0; i <= 1.0; i = i + 0.1) 
        {//50% de transparencia
            String val = i + "F";
            float f = Float.parseFloat(val);
            this.setOpacity(f);
            try {
                Thread.sleep(50);
            } catch (InterruptedException e) 
            {
            }
        }
        AnimationClass anim = new AnimationClass();
        anim.jLabelXRight(-400, 100, 10, 10, jLabelImagen);
    }//GEN-LAST:event_formWindowOpened

    private void jTextNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombre1ActionPerformed

    private void jTextNombre1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNombre1KeyReleased
        if(jTextNombre1.getText().isEmpty()){
            jTextNombre1.setBackground(rojoos);
        }else{
            jTextNombre1.setBackground(blancoo);
        }
    }//GEN-LAST:event_jTextNombre1KeyReleased

    private void jTextUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextUsuarioKeyReleased
        if(jTextUsuario.getText().isEmpty()){
            jTextUsuario.setBackground(rojoos);
        }else{
            int result = metodoSql.compararUsuario(jTextUsuario.getText());
            if(result==1){
                jTextUsuario.setBackground(rojis);
            }else{
                jTextUsuario.setBackground(verdesito);
            }
        }
    }//GEN-LAST:event_jTextUsuarioKeyReleased

    private void jTextApellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextApellidoKeyReleased
        if(jTextApellido.getText().isEmpty()){
            jTextApellido.setBackground(rojoos);
        }else{
            jTextApellido.setBackground(blancoo);
        }
    }//GEN-LAST:event_jTextApellidoKeyReleased

    private void jTextContraseña1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextContraseña1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextContraseña1ActionPerformed

    private void jTextContraseña1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextContraseña1KeyReleased
        if(jTextContraseña1.getText().isEmpty()){
            jTextContraseña1.setBackground(rojoos);
        }else{
            jTextContraseña1.setBackground(blancoo);
        }
    }//GEN-LAST:event_jTextContraseña1KeyReleased

    private void jTextCorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextCorreoKeyReleased
        if(jTextCorreo.getText().isEmpty()){
            jTextCorreo.setBackground(blancoo);
        }else{
            if(!jTextCorreo.getText().contains("@") || !jTextCorreo.getText().contains(".")){
                jTextCorreo.setBackground(rojis);
            }else{
                jTextCorreo.setBackground(blancoo);
            }
        }
    }//GEN-LAST:event_jTextCorreoKeyReleased

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        String contraseña = jTextContraseña1.getText();
        String confContraseña = jTextConfirmarContraseña.getText();
        String nombre = jTextNombre1.getText();
        String apellido = jTextApellido.getText();
        String email = jTextCorreo.getText();
        String usuario = jTextUsuario.getText();
        if(contraseña.equals("") && confContraseña.equals("") && nombre.equals("") && apellido.equals("") && email.equals("") && usuario.equals("")){
            animacion.jPanelYArriba(30, -470, 10, 5, jPanelCrear);
            animacion.jPanelXDerecha(-770, 0, 10, 5, jPanelInterface);
            animacionInicial().start();
            limpiar();
        }else{
            int dialog = JOptionPane.YES_NO_OPTION;
            int result = JOptionPane.showConfirmDialog(null, "Seguro que quiere cancelar", "EXIT", dialog);
            if(result == 0){
                animacion.jPanelYArriba(30, -470, 10, 5, jPanelCrear);
                animacion.jPanelXDerecha(-770, 0, 10, 5, jPanelInterface);
                animacionInicial().start();
                limpiar();
            }
        }
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jTextConfirmarContraseñaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextConfirmarContraseñaKeyReleased
        if(jTextConfirmarContraseña.getText().isEmpty()){
            jTextConfirmarContraseña.setBackground(blancoo);
        }else{
            if(!jTextContraseña1.getText().equals(jTextConfirmarContraseña.getText())){
                jTextConfirmarContraseña.setBackground(rojis);
            }else{
                jTextConfirmarContraseña.setBackground(verdesito);
            }
        }
    }//GEN-LAST:event_jTextConfirmarContraseñaKeyReleased

    private void jButtonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCrearActionPerformed
        String contraseña = jTextContraseña1.getText();
        String confContraseña = jTextConfirmarContraseña.getText();
        String nombre = jTextNombre1.getText();
        String apellido = jTextApellido.getText();
        String email = jTextCorreo.getText();
        String usuario = jTextUsuario.getText();
        validar();
        if(contraseña.equals("") || confContraseña.equals("") || nombre.equals("") || apellido.equals("") || email.equals("") || usuario.equals("")){
            JOptionPane.showMessageDialog(null,"Los campos resaltados son obligatorios");
        }else{
            if(aceptar){
                JOptionPane.showMessageDialog(null,"Correo no valido");
            }else{
                if(contraseña.equals(confContraseña)){
                    int result = metodoSql.compararUsuario(usuario);
                    if(result==0){
                        int i = metodoSql.guardar(nombre, apellido, email, contraseña, usuario);
                        if(i>0){
                            JOptionPane.showMessageDialog(this,"¡Cuenta creada exitosamente!");
                            animacion.jPanelYArriba(30, -470, 10, 5, jPanelCrear);
                            animacion.jPanelXDerecha(-770, 0, 10, 5, jPanelInterface);
                            animacionInicial().start();
                            limpiar();
                        }else{
                            JOptionPane.showMessageDialog(this,"¡Error en la creacion de cuenta!");
                        }
                    }else{
                        JOptionPane.showMessageDialog(null, "Ese usuario ya existe. Ingrese otro");
                    }
                }else{
                    JOptionPane.showMessageDialog(null,"Las contraseñas no coinciden");
                }
            }
        }
    }//GEN-LAST:event_jButtonCrearActionPerformed

    private void jButtonCrearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCrearMouseEntered
        jButtonCrear.setBackground(Color.white);
        jButtonCrear.setForeground(rojoos);
    }//GEN-LAST:event_jButtonCrearMouseEntered

    private void jButtonCrearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCrearMouseExited
        jButtonCrear.setBackground(rojoos);
        jButtonCrear.setForeground(Color.white);
    }//GEN-LAST:event_jButtonCrearMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JButton jButtonCrear;
    private javax.swing.JButton jButtonCrearCuenta;
    private javax.swing.JButton jButtonIngresar;
    private javax.swing.JButton jButtonMinimizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelApe;
    private javax.swing.JLabel jLabelCof;
    private javax.swing.JLabel jLabelCon;
    private javax.swing.JLabel jLabelCor;
    private javax.swing.JLabel jLabelImagen;
    private javax.swing.JLabel jLabelImagen1;
    private javax.swing.JLabel jLabelImagen2;
    private javax.swing.JLabel jLabelImagen3;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JLabel jLabelUsu;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelBarra;
    private javax.swing.JPanel jPanelCrear;
    private javax.swing.JPanel jPanelInterface;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField jTextApellido;
    private javax.swing.JPasswordField jTextConfirmarContraseña;
    private javax.swing.JPasswordField jTextContraseña;
    private javax.swing.JPasswordField jTextContraseña1;
    private javax.swing.JTextField jTextCorreo;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextNombre1;
    private javax.swing.JTextField jTextUsuario;
    // End of variables declaration//GEN-END:variables
}
